### ISSUE TITLE
Repository too big

### ISSUE THREAD

**Issue by camilonova** [koehlma/pygrooveshark#22]
![screen shot 2015-04-24 at 8 50 57 am](https://cloud.githubusercontent.com/assets/202559/7319959/1804861e-ea5f-11e4-8c3d-9ae3e69d24e9.png)

84mb seems like a lot.

Looking at the repo:

```
166M	webapp/www/desktop/extjs
```

Seems that folder is taking too much, could it be possible to get it from somewhere else, so you can avoid all that space into the repository?

**Comment by koehlma** [comment]
Sure, it was a bad idea to put these files in the repository.

**Comment by camilonova** [comment]
@koehlma what about if you create a separate repository for the examples?

**Comment by camilonova** [comment]
Also can you please #23 so I can add it as a requirement for https://github.com/camilonova/mopidy-grooveshark

**Comment by koehlma** [comment]
I do not think that a separate repository would be necessary because there are only a few examples. I just created a release 3.1.
